# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ImPact_toolbox_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_APIRequestDialogBase(object):
    def setupUi(self, APIRequestDialogBase):
        APIRequestDialogBase.setObjectName("APIRequestDialogBase")
        APIRequestDialogBase.setEnabled(True)
        APIRequestDialogBase.resize(855, 767)
        APIRequestDialogBase.setMaximumSize(QtCore.QSize(16777215, 16777215))
        APIRequestDialogBase.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        APIRequestDialogBase.setWindowIcon(icon)
        APIRequestDialogBase.setStyleSheet("")
        APIRequestDialogBase.setSizeGripEnabled(False)
        APIRequestDialogBase.setModal(False)
        self.gridLayout_6 = QtWidgets.QGridLayout(APIRequestDialogBase)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.KeyHolder = QtWidgets.QLineEdit(APIRequestDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.KeyHolder.sizePolicy().hasHeightForWidth())
        self.KeyHolder.setSizePolicy(sizePolicy)
        self.KeyHolder.setClearButtonEnabled(True)
        self.KeyHolder.setObjectName("KeyHolder")
        self.gridLayout_6.addWidget(self.KeyHolder, 1, 1, 1, 3)
        self.label_2 = QtWidgets.QLabel(APIRequestDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(APIRequestDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 7, 0, 1, 2)
        self.button_box = QtWidgets.QDialogButtonBox(APIRequestDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_box.sizePolicy().hasHeightForWidth())
        self.button_box.setSizePolicy(sizePolicy)
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.gridLayout_6.addWidget(self.button_box, 10, 0, 1, 4)
        self.toolBox = QtWidgets.QToolBox(APIRequestDialogBase)
        self.toolBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.toolBox.setFont(font)
        self.toolBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.toolBox.setAcceptDrops(False)
        self.toolBox.setAutoFillBackground(False)
        self.toolBox.setStyleSheet("")
        self.toolBox.setFrameShape(QtWidgets.QFrame.Box)
        self.toolBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.toolBox.setLineWidth(1)
        self.toolBox.setMidLineWidth(2)
        self.toolBox.setObjectName("toolBox")
        self.routingTab = QtWidgets.QWidget()
        self.routingTab.setGeometry(QtCore.QRect(0, 0, 825, 549))
        self.routingTab.setObjectName("routingTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.routingTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.routingTab)
        self.textBrowser.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setTabChangesFocus(False)
        self.textBrowser.setUndoRedoEnabled(False)
        self.textBrowser.setReadOnly(True)
        self.textBrowser.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.textBrowser.setOpenExternalLinks(True)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_3.addWidget(self.textBrowser, 0, 2, 2, 1)
        self.routingWgt = QtWidgets.QTabWidget(self.routingTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.routingWgt.sizePolicy().hasHeightForWidth())
        self.routingWgt.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.routingWgt.setFont(font)
        self.routingWgt.setFocusPolicy(QtCore.Qt.TabFocus)
        self.routingWgt.setToolTip("")
        self.routingWgt.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.routingWgt.setObjectName("routingWgt")
        self.routingTab1 = QtWidgets.QWidget()
        self.routingTab1.setObjectName("routingTab1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.routingTab1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 9, 2, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.routingTab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 2, 0, 1, 1)
        self.routingTab1_profileCbx = QtWidgets.QComboBox(self.routingTab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.routingTab1_profileCbx.sizePolicy().hasHeightForWidth())
        self.routingTab1_profileCbx.setSizePolicy(sizePolicy)
        self.routingTab1_profileCbx.setEditable(False)
        self.routingTab1_profileCbx.setObjectName("routingTab1_profileCbx")
        self.routingTab1_profileCbx.addItem("")
        self.routingTab1_profileCbx.addItem("")
        self.routingTab1_profileCbx.addItem("")
        self.routingTab1_profileCbx.addItem("")
        self.routingTab1_profileCbx.addItem("")
        self.routingTab1_profileCbx.addItem("")
        self.routingTab1_profileCbx.addItem("")
        self.gridLayout_2.addWidget(self.routingTab1_profileCbx, 1, 1, 1, 2)
        self.label_22 = QtWidgets.QLabel(self.routingTab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 1, 0, 1, 1)
        self.routingTab1_mColorBtn = QgsColorButton(self.routingTab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.routingTab1_mColorBtn.sizePolicy().hasHeightForWidth())
        self.routingTab1_mColorBtn.setSizePolicy(sizePolicy)
        self.routingTab1_mColorBtn.setMouseTracking(False)
        self.routingTab1_mColorBtn.setObjectName("routingTab1_mColorBtn")
        self.gridLayout_2.addWidget(self.routingTab1_mColorBtn, 7, 1, 2, 2)
        self.routingTab1_mLayers = QgsMapLayerComboBox(self.routingTab1)
        self.routingTab1_mLayers.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.routingTab1_mLayers.sizePolicy().hasHeightForWidth())
        self.routingTab1_mLayers.setSizePolicy(sizePolicy)
        self.routingTab1_mLayers.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.routingTab1_mLayers.setObjectName("routingTab1_mLayers")
        self.gridLayout_2.addWidget(self.routingTab1_mLayers, 0, 1, 1, 2)
        self.routingTab1_outDirTxt = QtWidgets.QLineEdit(self.routingTab1)
        self.routingTab1_outDirTxt.setText("")
        self.routingTab1_outDirTxt.setReadOnly(True)
        self.routingTab1_outDirTxt.setObjectName("routingTab1_outDirTxt")
        self.gridLayout_2.addWidget(self.routingTab1_outDirTxt, 2, 2, 1, 1)
        self.routingTab1_widthNum = QtWidgets.QSpinBox(self.routingTab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.routingTab1_widthNum.sizePolicy().hasHeightForWidth())
        self.routingTab1_widthNum.setSizePolicy(sizePolicy)
        self.routingTab1_widthNum.setMinimum(1)
        self.routingTab1_widthNum.setMaximum(10)
        self.routingTab1_widthNum.setObjectName("routingTab1_widthNum")
        self.gridLayout_2.addWidget(self.routingTab1_widthNum, 5, 1, 1, 2)
        self.label_24 = QtWidgets.QLabel(self.routingTab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setAutoFillBackground(False)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 7, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.routingTab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.routingTab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 5, 0, 1, 1)
        self.routingtab1_SepRoutes_Cbx = QtWidgets.QCheckBox(self.routingTab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.routingtab1_SepRoutes_Cbx.sizePolicy().hasHeightForWidth())
        self.routingtab1_SepRoutes_Cbx.setSizePolicy(sizePolicy)
        self.routingtab1_SepRoutes_Cbx.setObjectName("routingtab1_SepRoutes_Cbx")
        self.gridLayout_2.addWidget(self.routingtab1_SepRoutes_Cbx, 4, 0, 1, 1)
        self.routingTab1_OutDirBtn = QtWidgets.QPushButton(self.routingTab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.routingTab1_OutDirBtn.sizePolicy().hasHeightForWidth())
        self.routingTab1_OutDirBtn.setSizePolicy(sizePolicy)
        self.routingTab1_OutDirBtn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.routingTab1_OutDirBtn.setObjectName("routingTab1_OutDirBtn")
        self.gridLayout_2.addWidget(self.routingTab1_OutDirBtn, 2, 1, 1, 1)
        self.routingWgt.addTab(self.routingTab1, "")
        self.routingTab2 = QtWidgets.QWidget()
        self.routingTab2.setObjectName("routingTab2")
        self.gridLayout = QtWidgets.QGridLayout(self.routingTab2)
        self.gridLayout.setObjectName("gridLayout")
        self.routingTab2_profileCbx = QtWidgets.QComboBox(self.routingTab2)
        self.routingTab2_profileCbx.setEditable(False)
        self.routingTab2_profileCbx.setObjectName("routingTab2_profileCbx")
        self.routingTab2_profileCbx.addItem("")
        self.routingTab2_profileCbx.addItem("")
        self.routingTab2_profileCbx.addItem("")
        self.routingTab2_profileCbx.addItem("")
        self.routingTab2_profileCbx.addItem("")
        self.routingTab2_profileCbx.addItem("")
        self.routingTab2_profileCbx.addItem("")
        self.gridLayout.addWidget(self.routingTab2_profileCbx, 2, 1, 1, 4)
        self.routingTab2_outDirTxt = QtWidgets.QLineEdit(self.routingTab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.routingTab2_outDirTxt.sizePolicy().hasHeightForWidth())
        self.routingTab2_outDirTxt.setSizePolicy(sizePolicy)
        self.routingTab2_outDirTxt.setText("")
        self.routingTab2_outDirTxt.setReadOnly(True)
        self.routingTab2_outDirTxt.setObjectName("routingTab2_outDirTxt")
        self.gridLayout.addWidget(self.routingTab2_outDirTxt, 3, 2, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 9, 3, 1, 2)
        self.label_28 = QtWidgets.QLabel(self.routingTab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28, 1, 0, 1, 1)
        self.routingtab2_SepRoutes_Cbx = QtWidgets.QCheckBox(self.routingTab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.routingtab2_SepRoutes_Cbx.sizePolicy().hasHeightForWidth())
        self.routingtab2_SepRoutes_Cbx.setSizePolicy(sizePolicy)
        self.routingtab2_SepRoutes_Cbx.setObjectName("routingtab2_SepRoutes_Cbx")
        self.gridLayout.addWidget(self.routingtab2_SepRoutes_Cbx, 4, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.routingTab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        self.label_29.setObjectName("label_29")
        self.gridLayout.addWidget(self.label_29, 8, 0, 1, 1)
        self.routingTab2_O_mLayers = QgsMapLayerComboBox(self.routingTab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.routingTab2_O_mLayers.sizePolicy().hasHeightForWidth())
        self.routingTab2_O_mLayers.setSizePolicy(sizePolicy)
        self.routingTab2_O_mLayers.setObjectName("routingTab2_O_mLayers")
        self.gridLayout.addWidget(self.routingTab2_O_mLayers, 0, 1, 1, 4)
        self.routingTab2_mColorBtn = QgsColorButton(self.routingTab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.routingTab2_mColorBtn.sizePolicy().hasHeightForWidth())
        self.routingTab2_mColorBtn.setSizePolicy(sizePolicy)
        self.routingTab2_mColorBtn.setMouseTracking(False)
        self.routingTab2_mColorBtn.setObjectName("routingTab2_mColorBtn")
        self.gridLayout.addWidget(self.routingTab2_mColorBtn, 8, 1, 1, 4)
        self.label_26 = QtWidgets.QLabel(self.routingTab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 2, 0, 1, 1)
        self.routingTab2_D_mLayers = QgsMapLayerComboBox(self.routingTab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.routingTab2_D_mLayers.sizePolicy().hasHeightForWidth())
        self.routingTab2_D_mLayers.setSizePolicy(sizePolicy)
        self.routingTab2_D_mLayers.setObjectName("routingTab2_D_mLayers")
        self.gridLayout.addWidget(self.routingTab2_D_mLayers, 1, 1, 1, 4)
        self.label_25 = QtWidgets.QLabel(self.routingTab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 0, 0, 1, 1)
        self.routingTab2_widthNum = QtWidgets.QSpinBox(self.routingTab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.routingTab2_widthNum.sizePolicy().hasHeightForWidth())
        self.routingTab2_widthNum.setSizePolicy(sizePolicy)
        self.routingTab2_widthNum.setMinimum(1)
        self.routingTab2_widthNum.setMaximum(10)
        self.routingTab2_widthNum.setObjectName("routingTab2_widthNum")
        self.gridLayout.addWidget(self.routingTab2_widthNum, 5, 1, 1, 4)
        self.routingTab2_OutDirBtn = QtWidgets.QPushButton(self.routingTab2)
        self.routingTab2_OutDirBtn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.routingTab2_OutDirBtn.setObjectName("routingTab2_OutDirBtn")
        self.gridLayout.addWidget(self.routingTab2_OutDirBtn, 3, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.routingTab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        self.label_30.setObjectName("label_30")
        self.gridLayout.addWidget(self.label_30, 5, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.routingTab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setObjectName("label_27")
        self.gridLayout.addWidget(self.label_27, 3, 0, 1, 1)
        self.routingWgt.addTab(self.routingTab2, "")
        self.gridLayout_3.addWidget(self.routingWgt, 0, 0, 2, 2)
        self.toolBox.addItem(self.routingTab, "")
        self.shortcutTab = QtWidgets.QWidget()
        self.shortcutTab.setGeometry(QtCore.QRect(0, 0, 825, 549))
        self.shortcutTab.setObjectName("shortcutTab")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.shortcutTab)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.shortcutTab)
        self.textBrowser_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_2.sizePolicy().hasHeightForWidth())
        self.textBrowser_2.setSizePolicy(sizePolicy)
        self.textBrowser_2.setTabChangesFocus(False)
        self.textBrowser_2.setUndoRedoEnabled(False)
        self.textBrowser_2.setReadOnly(True)
        self.textBrowser_2.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.textBrowser_2.setOpenExternalLinks(True)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.gridLayout_7.addWidget(self.textBrowser_2, 0, 1, 1, 1)
        self.shortcutWgt = QtWidgets.QTabWidget(self.shortcutTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shortcutWgt.sizePolicy().hasHeightForWidth())
        self.shortcutWgt.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.shortcutWgt.setFont(font)
        self.shortcutWgt.setFocusPolicy(QtCore.Qt.TabFocus)
        self.shortcutWgt.setToolTip("")
        self.shortcutWgt.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.shortcutWgt.setObjectName("shortcutWgt")
        self.shortcutTab1 = QtWidgets.QWidget()
        self.shortcutTab1.setObjectName("shortcutTab1")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.shortcutTab1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.shortcutTab1_ClientTxt = QtWidgets.QLineEdit(self.shortcutTab1)
        self.shortcutTab1_ClientTxt.setClearButtonEnabled(True)
        self.shortcutTab1_ClientTxt.setObjectName("shortcutTab1_ClientTxt")
        self.gridLayout_4.addWidget(self.shortcutTab1_ClientTxt, 1, 1, 1, 2)
        self.shortcutTab1_outDirTxt = QtWidgets.QLineEdit(self.shortcutTab1)
        self.shortcutTab1_outDirTxt.setText("")
        self.shortcutTab1_outDirTxt.setReadOnly(True)
        self.shortcutTab1_outDirTxt.setObjectName("shortcutTab1_outDirTxt")
        self.gridLayout_4.addWidget(self.shortcutTab1_outDirTxt, 5, 2, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.shortcutTab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        self.label_31.setObjectName("label_31")
        self.gridLayout_4.addWidget(self.label_31, 5, 0, 1, 1)
        self.shortcutTab1_widthNum = QtWidgets.QSpinBox(self.shortcutTab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shortcutTab1_widthNum.sizePolicy().hasHeightForWidth())
        self.shortcutTab1_widthNum.setSizePolicy(sizePolicy)
        self.shortcutTab1_widthNum.setMinimum(1)
        self.shortcutTab1_widthNum.setMaximum(10)
        self.shortcutTab1_widthNum.setObjectName("shortcutTab1_widthNum")
        self.gridLayout_4.addWidget(self.shortcutTab1_widthNum, 8, 1, 1, 2)
        self.label_34 = QtWidgets.QLabel(self.shortcutTab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_34.sizePolicy().hasHeightForWidth())
        self.label_34.setSizePolicy(sizePolicy)
        self.label_34.setObjectName("label_34")
        self.gridLayout_4.addWidget(self.label_34, 8, 0, 1, 1)
        self.shortcutTab1_SepRoutes_Cbx = QtWidgets.QCheckBox(self.shortcutTab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shortcutTab1_SepRoutes_Cbx.sizePolicy().hasHeightForWidth())
        self.shortcutTab1_SepRoutes_Cbx.setSizePolicy(sizePolicy)
        self.shortcutTab1_SepRoutes_Cbx.setObjectName("shortcutTab1_SepRoutes_Cbx")
        self.gridLayout_4.addWidget(self.shortcutTab1_SepRoutes_Cbx, 7, 0, 1, 1)
        self.shortcutTab1_OutDirBtn = QtWidgets.QPushButton(self.shortcutTab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shortcutTab1_OutDirBtn.sizePolicy().hasHeightForWidth())
        self.shortcutTab1_OutDirBtn.setSizePolicy(sizePolicy)
        self.shortcutTab1_OutDirBtn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.shortcutTab1_OutDirBtn.setObjectName("shortcutTab1_OutDirBtn")
        self.gridLayout_4.addWidget(self.shortcutTab1_OutDirBtn, 5, 1, 1, 1)
        self.shortcutTab1_mLayers = QgsMapLayerComboBox(self.shortcutTab1)
        self.shortcutTab1_mLayers.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shortcutTab1_mLayers.sizePolicy().hasHeightForWidth())
        self.shortcutTab1_mLayers.setSizePolicy(sizePolicy)
        self.shortcutTab1_mLayers.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.shortcutTab1_mLayers.setObjectName("shortcutTab1_mLayers")
        self.gridLayout_4.addWidget(self.shortcutTab1_mLayers, 0, 1, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.shortcutTab1)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.shortcutTab1)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.shortcutTab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 0, 0, 1, 1)
        self.shortcutTab1_profileCbx = QtWidgets.QComboBox(self.shortcutTab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shortcutTab1_profileCbx.sizePolicy().hasHeightForWidth())
        self.shortcutTab1_profileCbx.setSizePolicy(sizePolicy)
        self.shortcutTab1_profileCbx.setEditable(False)
        self.shortcutTab1_profileCbx.setObjectName("shortcutTab1_profileCbx")
        self.shortcutTab1_profileCbx.addItem("")
        self.shortcutTab1_profileCbx.addItem("")
        self.shortcutTab1_profileCbx.addItem("")
        self.shortcutTab1_profileCbx.addItem("")
        self.shortcutTab1_profileCbx.addItem("")
        self.shortcutTab1_profileCbx.addItem("")
        self.shortcutTab1_profileCbx.addItem("")
        self.gridLayout_4.addWidget(self.shortcutTab1_profileCbx, 4, 1, 1, 2)
        self.label_33 = QtWidgets.QLabel(self.shortcutTab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_33.sizePolicy().hasHeightForWidth())
        self.label_33.setSizePolicy(sizePolicy)
        self.label_33.setAutoFillBackground(False)
        self.label_33.setObjectName("label_33")
        self.gridLayout_4.addWidget(self.label_33, 10, 0, 1, 1)
        self.shortcutTab1_NetworkTxt = QtWidgets.QLineEdit(self.shortcutTab1)
        self.shortcutTab1_NetworkTxt.setClearButtonEnabled(True)
        self.shortcutTab1_NetworkTxt.setObjectName("shortcutTab1_NetworkTxt")
        self.gridLayout_4.addWidget(self.shortcutTab1_NetworkTxt, 2, 1, 1, 2)
        self.label_9 = QtWidgets.QLabel(self.shortcutTab1)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 3, 0, 1, 1)
        self.shortcutTab1_mColorBtn = QgsColorButton(self.shortcutTab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shortcutTab1_mColorBtn.sizePolicy().hasHeightForWidth())
        self.shortcutTab1_mColorBtn.setSizePolicy(sizePolicy)
        self.shortcutTab1_mColorBtn.setMouseTracking(False)
        self.shortcutTab1_mColorBtn.setObjectName("shortcutTab1_mColorBtn")
        self.gridLayout_4.addWidget(self.shortcutTab1_mColorBtn, 10, 1, 2, 2)
        self.label_32 = QtWidgets.QLabel(self.shortcutTab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_32.sizePolicy().hasHeightForWidth())
        self.label_32.setSizePolicy(sizePolicy)
        self.label_32.setObjectName("label_32")
        self.gridLayout_4.addWidget(self.label_32, 4, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem2, 12, 2, 1, 1)
        self.shortcutTab1_InstanceCbx = QtWidgets.QComboBox(self.shortcutTab1)
        self.shortcutTab1_InstanceCbx.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.shortcutTab1_InstanceCbx.setObjectName("shortcutTab1_InstanceCbx")
        self.shortcutTab1_InstanceCbx.addItem("")
        self.shortcutTab1_InstanceCbx.addItem("")
        self.shortcutTab1_InstanceCbx.addItem("")
        self.shortcutTab1_InstanceCbx.addItem("")
        self.shortcutTab1_InstanceCbx.addItem("")
        self.shortcutTab1_InstanceCbx.addItem("")
        self.shortcutTab1_InstanceCbx.addItem("")
        self.shortcutTab1_InstanceCbx.addItem("")
        self.shortcutTab1_InstanceCbx.addItem("")
        self.shortcutTab1_InstanceCbx.addItem("")
        self.gridLayout_4.addWidget(self.shortcutTab1_InstanceCbx, 3, 1, 1, 2)
        self.shortcutWgt.addTab(self.shortcutTab1, "")
        self.shortcutTab_2 = QtWidgets.QWidget()
        self.shortcutTab_2.setObjectName("shortcutTab_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.shortcutTab_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.shortcutTab2_OutDirBtn = QtWidgets.QPushButton(self.shortcutTab_2)
        self.shortcutTab2_OutDirBtn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.shortcutTab2_OutDirBtn.setObjectName("shortcutTab2_OutDirBtn")
        self.gridLayout_5.addWidget(self.shortcutTab2_OutDirBtn, 6, 1, 1, 1)
        self.shortcutTab2_profileCbx = QtWidgets.QComboBox(self.shortcutTab_2)
        self.shortcutTab2_profileCbx.setEditable(False)
        self.shortcutTab2_profileCbx.setObjectName("shortcutTab2_profileCbx")
        self.shortcutTab2_profileCbx.addItem("")
        self.shortcutTab2_profileCbx.addItem("")
        self.shortcutTab2_profileCbx.addItem("")
        self.shortcutTab2_profileCbx.addItem("")
        self.shortcutTab2_profileCbx.addItem("")
        self.shortcutTab2_profileCbx.addItem("")
        self.shortcutTab2_profileCbx.addItem("")
        self.gridLayout_5.addWidget(self.shortcutTab2_profileCbx, 5, 1, 1, 4)
        self.shortcutTab2_O_mLayers = QgsMapLayerComboBox(self.shortcutTab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shortcutTab2_O_mLayers.sizePolicy().hasHeightForWidth())
        self.shortcutTab2_O_mLayers.setSizePolicy(sizePolicy)
        self.shortcutTab2_O_mLayers.setObjectName("shortcutTab2_O_mLayers")
        self.gridLayout_5.addWidget(self.shortcutTab2_O_mLayers, 0, 1, 1, 4)
        self.label_38 = QtWidgets.QLabel(self.shortcutTab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_38.sizePolicy().hasHeightForWidth())
        self.label_38.setSizePolicy(sizePolicy)
        self.label_38.setObjectName("label_38")
        self.gridLayout_5.addWidget(self.label_38, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem3, 12, 3, 1, 2)
        self.shortcutTab2_NetworkTxt = QtWidgets.QLineEdit(self.shortcutTab_2)
        self.shortcutTab2_NetworkTxt.setClearButtonEnabled(True)
        self.shortcutTab2_NetworkTxt.setObjectName("shortcutTab2_NetworkTxt")
        self.gridLayout_5.addWidget(self.shortcutTab2_NetworkTxt, 3, 1, 1, 4)
        self.label_39 = QtWidgets.QLabel(self.shortcutTab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_39.sizePolicy().hasHeightForWidth())
        self.label_39.setSizePolicy(sizePolicy)
        self.label_39.setObjectName("label_39")
        self.gridLayout_5.addWidget(self.label_39, 8, 0, 1, 1)
        self.shortcutTab2_mColorBtn = QgsColorButton(self.shortcutTab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shortcutTab2_mColorBtn.sizePolicy().hasHeightForWidth())
        self.shortcutTab2_mColorBtn.setSizePolicy(sizePolicy)
        self.shortcutTab2_mColorBtn.setMouseTracking(False)
        self.shortcutTab2_mColorBtn.setObjectName("shortcutTab2_mColorBtn")
        self.gridLayout_5.addWidget(self.shortcutTab2_mColorBtn, 11, 1, 1, 4)
        self.shortcutTab2_D_mLayers = QgsMapLayerComboBox(self.shortcutTab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shortcutTab2_D_mLayers.sizePolicy().hasHeightForWidth())
        self.shortcutTab2_D_mLayers.setSizePolicy(sizePolicy)
        self.shortcutTab2_D_mLayers.setObjectName("shortcutTab2_D_mLayers")
        self.gridLayout_5.addWidget(self.shortcutTab2_D_mLayers, 1, 1, 1, 4)
        self.label_37 = QtWidgets.QLabel(self.shortcutTab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_37.sizePolicy().hasHeightForWidth())
        self.label_37.setSizePolicy(sizePolicy)
        self.label_37.setObjectName("label_37")
        self.gridLayout_5.addWidget(self.label_37, 5, 0, 1, 1)
        self.shortcutTab2_outDirTxt = QtWidgets.QLineEdit(self.shortcutTab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shortcutTab2_outDirTxt.sizePolicy().hasHeightForWidth())
        self.shortcutTab2_outDirTxt.setSizePolicy(sizePolicy)
        self.shortcutTab2_outDirTxt.setText("")
        self.shortcutTab2_outDirTxt.setReadOnly(True)
        self.shortcutTab2_outDirTxt.setObjectName("shortcutTab2_outDirTxt")
        self.gridLayout_5.addWidget(self.shortcutTab2_outDirTxt, 6, 2, 1, 3)
        self.label_36 = QtWidgets.QLabel(self.shortcutTab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_36.sizePolicy().hasHeightForWidth())
        self.label_36.setSizePolicy(sizePolicy)
        self.label_36.setObjectName("label_36")
        self.gridLayout_5.addWidget(self.label_36, 11, 0, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.shortcutTab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_40.sizePolicy().hasHeightForWidth())
        self.label_40.setSizePolicy(sizePolicy)
        self.label_40.setObjectName("label_40")
        self.gridLayout_5.addWidget(self.label_40, 6, 0, 1, 1)
        self.shortcutTab2_SepRoutes_Cbx = QtWidgets.QCheckBox(self.shortcutTab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shortcutTab2_SepRoutes_Cbx.sizePolicy().hasHeightForWidth())
        self.shortcutTab2_SepRoutes_Cbx.setSizePolicy(sizePolicy)
        self.shortcutTab2_SepRoutes_Cbx.setObjectName("shortcutTab2_SepRoutes_Cbx")
        self.gridLayout_5.addWidget(self.shortcutTab2_SepRoutes_Cbx, 7, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.shortcutTab_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.shortcutTab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_35.sizePolicy().hasHeightForWidth())
        self.label_35.setSizePolicy(sizePolicy)
        self.label_35.setObjectName("label_35")
        self.gridLayout_5.addWidget(self.label_35, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.shortcutTab_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 3, 0, 1, 1)
        self.shortcutTab2_widthNum = QtWidgets.QSpinBox(self.shortcutTab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shortcutTab2_widthNum.sizePolicy().hasHeightForWidth())
        self.shortcutTab2_widthNum.setSizePolicy(sizePolicy)
        self.shortcutTab2_widthNum.setMinimum(1)
        self.shortcutTab2_widthNum.setMaximum(10)
        self.shortcutTab2_widthNum.setObjectName("shortcutTab2_widthNum")
        self.gridLayout_5.addWidget(self.shortcutTab2_widthNum, 8, 1, 1, 4)
        self.label_11 = QtWidgets.QLabel(self.shortcutTab_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_5.addWidget(self.label_11, 4, 0, 1, 1)
        self.shortcutTab2_ClientTxt = QtWidgets.QLineEdit(self.shortcutTab_2)
        self.shortcutTab2_ClientTxt.setClearButtonEnabled(True)
        self.shortcutTab2_ClientTxt.setObjectName("shortcutTab2_ClientTxt")
        self.gridLayout_5.addWidget(self.shortcutTab2_ClientTxt, 2, 1, 1, 4)
        self.shortcutTab2_InstanceCbx = QtWidgets.QComboBox(self.shortcutTab_2)
        self.shortcutTab2_InstanceCbx.setObjectName("shortcutTab2_InstanceCbx")
        self.shortcutTab2_InstanceCbx.addItem("")
        self.shortcutTab2_InstanceCbx.addItem("")
        self.shortcutTab2_InstanceCbx.addItem("")
        self.shortcutTab2_InstanceCbx.addItem("")
        self.shortcutTab2_InstanceCbx.addItem("")
        self.shortcutTab2_InstanceCbx.addItem("")
        self.shortcutTab2_InstanceCbx.addItem("")
        self.shortcutTab2_InstanceCbx.addItem("")
        self.shortcutTab2_InstanceCbx.addItem("")
        self.shortcutTab2_InstanceCbx.addItem("")
        self.gridLayout_5.addWidget(self.shortcutTab2_InstanceCbx, 4, 1, 1, 4)
        self.shortcutWgt.addTab(self.shortcutTab_2, "")
        self.gridLayout_7.addWidget(self.shortcutWgt, 0, 0, 1, 1)
        self.toolBox.addItem(self.shortcutTab, "")
        self.gridLayout_6.addWidget(self.toolBox, 5, 0, 1, 4)
        self.label = QtWidgets.QLabel(APIRequestDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 4)
        self.KeyHolder.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        self.button_box.raise_()
        self.label.raise_()
        self.toolBox.raise_()

        self.retranslateUi(APIRequestDialogBase)
        self.toolBox.setCurrentIndex(0)
        self.toolBox.layout().setSpacing(10)
        self.routingWgt.setCurrentIndex(0)
        self.shortcutWgt.setCurrentIndex(0)
        self.button_box.accepted.connect(APIRequestDialogBase.accept)
        self.button_box.rejected.connect(APIRequestDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(APIRequestDialogBase)

    def retranslateUi(self, APIRequestDialogBase):
        _translate = QtCore.QCoreApplication.translate
        APIRequestDialogBase.setWindowTitle(_translate("APIRequestDialogBase", "ImPact ToolBox"))
        self.label_2.setText(_translate("APIRequestDialogBase", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">API Key </span><span style=\" font-size:9pt; font-weight:600; color:#ff0000;\">*</span></p></body></html>"))
        self.label_4.setText(_translate("APIRequestDialogBase", "<html><head/><body><p><span style=\" color:#ff0000;\">*</span> Indicates required field</p></body></html>"))
        self.textBrowser.setHtml(_translate("APIRequestDialogBase", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; text-decoration: underline;\">Application:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:400;\">This tab allows for routings based on the existing network: </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:12pt; text-decoration: underline;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">All POIs:</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:400;\"> between a set of Points of Interest (POIs) based on a given mode of transport (routing profile)</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:400;\">    </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">Origins to Destinations:</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:400;\"> from a set of Origins to a set of Destinations based on a given mode of transport (routing profile)</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-weight:400;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; text-decoration: underline;\">Fields Description:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:12pt; text-decoration: underline;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">API Key: </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:400;\">Insert your API key here . If you don’t have one, you can request via </span><a href=\"mailto:support@anyways.eu\"><span style=\" font-family:\'MS Shell Dlg 2\'; text-decoration: underline; color:#0000ff;\">email</span></a><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:400;\">.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\';\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt; text-decoration: underline;\">All POIs:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">Points of Interest (POIs):</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:400;\"> Select the layer that contains your points of interest.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">Profile: </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:400;\">Select your desired routing profile. For more information about routing profiles, please visit our </span><a href=\"https://docs.anyways.eu/routing-api/\"><span style=\" font-family:\'MS Shell Dlg 2\'; text-decoration: underline; color:#0000ff;\">documentation website</span></a><span style=\" font-family:\'MS Shell Dlg 2\';\">.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">Output Folder: </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:400;\">Select the folder in which you’d like to save the routings JSON file.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">Seperate Routing: </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:400;\">Check this box if you’d like to have routing between each pair of points saved as a separate JSON file in the folder you selected above and subsequently added in QGIS as separate layers. </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">Width &amp; Color:</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:400;\"> Choose the symbology of routing layer/s in QGIS.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-weight:400;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt; text-decoration: underline;\">Origins to Destinations:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">Origins: </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:400;\">Select the layer that contains your </span><span style=\" font-family:\'MS Shell Dlg 2\';\">Origin</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:400;\"> points.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">Destinations: </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:400;\">Select the layer that contains your </span><span style=\" font-family:\'MS Shell Dlg 2\';\">Desination</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:400;\"> points.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">Profile: </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:400;\">Select your desired routing profile. For more information about routing profiles, please visit our </span><a href=\"https://docs.anyways.eu/routing-api/\"><span style=\" font-family:\'MS Shell Dlg 2\'; text-decoration: underline; color:#0000ff;\">documentation website</span></a><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:400;\">.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">Output Folder: </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:400;\">Select the folder in which you’d like to save the routings JSON file.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">Seperate Routing: </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:400;\">Check this box if you’d like to have routing between each pair of points saved as a separate JSON file in the folder you selected above and subsequently added in QGIS as separate layers. </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">Width &amp; Color: </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:400;\">Choose the symbology of routing layer/s in QGIS.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-weight:400;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-weight:400;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-weight:400;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-weight:400;\"><br /></p></body></html>"))
        self.label_21.setText(_translate("APIRequestDialogBase", "<html><head/><body><p>Output folder <span style=\" color:#ff0000;\">*</span></p></body></html>"))
        self.routingTab1_profileCbx.setToolTip(_translate("APIRequestDialogBase", "Mode of travel"))
        self.routingTab1_profileCbx.setItemText(0, _translate("APIRequestDialogBase", "bicycle.fastest"))
        self.routingTab1_profileCbx.setItemText(1, _translate("APIRequestDialogBase", "bicycle.shortest"))
        self.routingTab1_profileCbx.setItemText(2, _translate("APIRequestDialogBase", "bicycle.networks"))
        self.routingTab1_profileCbx.setItemText(3, _translate("APIRequestDialogBase", "car"))
        self.routingTab1_profileCbx.setItemText(4, _translate("APIRequestDialogBase", "car.shortest"))
        self.routingTab1_profileCbx.setItemText(5, _translate("APIRequestDialogBase", "car.classifications"))
        self.routingTab1_profileCbx.setItemText(6, _translate("APIRequestDialogBase", "pedestrian.shortest"))
        self.label_22.setText(_translate("APIRequestDialogBase", "<html><head/><body><p>Profile <span style=\" color:#ff0000;\">*</span></p></body></html>"))
        self.routingTab1_widthNum.setSuffix(_translate("APIRequestDialogBase", " mm"))
        self.label_24.setText(_translate("APIRequestDialogBase", "Color"))
        self.label_6.setText(_translate("APIRequestDialogBase", "<html><head/><body><p>Points of Interest (POIs) <span style=\" color:#ff0000;\">*</span></p></body></html>"))
        self.label_23.setText(_translate("APIRequestDialogBase", "Width"))
        self.routingtab1_SepRoutes_Cbx.setText(_translate("APIRequestDialogBase", "Seperate Routings"))
        self.routingTab1_OutDirBtn.setText(_translate("APIRequestDialogBase", "..."))
        self.routingWgt.setTabText(self.routingWgt.indexOf(self.routingTab1), _translate("APIRequestDialogBase", "All POIs"))
        self.routingTab2.setToolTip(_translate("APIRequestDialogBase", "Connecting all Origins to all Destinations"))
        self.routingTab2_profileCbx.setToolTip(_translate("APIRequestDialogBase", "Mode of travel"))
        self.routingTab2_profileCbx.setItemText(0, _translate("APIRequestDialogBase", "bicycle.fastest"))
        self.routingTab2_profileCbx.setItemText(1, _translate("APIRequestDialogBase", "bicycle.shortest"))
        self.routingTab2_profileCbx.setItemText(2, _translate("APIRequestDialogBase", "bicycle.networks"))
        self.routingTab2_profileCbx.setItemText(3, _translate("APIRequestDialogBase", "car"))
        self.routingTab2_profileCbx.setItemText(4, _translate("APIRequestDialogBase", "car.shortest"))
        self.routingTab2_profileCbx.setItemText(5, _translate("APIRequestDialogBase", "car.classifications"))
        self.routingTab2_profileCbx.setItemText(6, _translate("APIRequestDialogBase", "pedestrian.shortest"))
        self.label_28.setText(_translate("APIRequestDialogBase", "<html><head/><body><p>Destinations <span style=\" color:#ff0000;\">*</span></p></body></html>"))
        self.routingtab2_SepRoutes_Cbx.setText(_translate("APIRequestDialogBase", "Seperate Routings"))
        self.label_29.setText(_translate("APIRequestDialogBase", "Color"))
        self.label_26.setText(_translate("APIRequestDialogBase", "<html><head/><body><p>Profile <span style=\" color:#ff0000;\">*</span></p></body></html>"))
        self.label_25.setText(_translate("APIRequestDialogBase", "<html><head/><body><p>Origins <span style=\" color:#ff0000;\">*</span></p></body></html>"))
        self.routingTab2_widthNum.setSuffix(_translate("APIRequestDialogBase", " mm"))
        self.routingTab2_OutDirBtn.setText(_translate("APIRequestDialogBase", "..."))
        self.label_30.setText(_translate("APIRequestDialogBase", "Width"))
        self.label_27.setText(_translate("APIRequestDialogBase", "<html><head/><body><p>Output folder <span style=\" color:#ff0000;\">*</span></p></body></html>"))
        self.routingWgt.setTabText(self.routingWgt.indexOf(self.routingTab2), _translate("APIRequestDialogBase", "Origins to Destinations"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.routingTab), _translate("APIRequestDialogBase", "Routing API"))
        self.textBrowser_2.setHtml(_translate("APIRequestDialogBase", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; text-decoration: underline;\">Application:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:400;\">This tab allows for scenario-based</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:400; vertical-align:super;\">1</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:400;\"> (e.g., road closures, changing directions, adding/removing a link to/from the existing road, cycling, and/or pedestrian network, etc.) routing:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:12pt; text-decoration: underline;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">All POIs:</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:400;\"> between a set of Points of Interest (POIs) based on a given mode of transport (routing profile)</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:400;\">    </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">Origins to Destinations:</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:400;\"> from a set of Origins to a set of Destinations based on a given mode of transport (routing profile)</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\';\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; text-decoration: underline;\">Fields Description:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:12pt; text-decoration: underline;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">API Key: </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:400;\">Insert your API key here . If you don’t have one, you can request via </span><a href=\"mailto:support@anyways.eu\"><span style=\" font-family:\'MS Shell Dlg 2\'; text-decoration: underline; color:#0000ff;\">email</span></a><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:400;\">.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\';\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt; text-decoration: underline;\">All POIs:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">Points of Interest (POIs):</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:400;\"> Select the layer that contains your points of interest.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">Instance: </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:400;\">Insert your ShortCut instance</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:400; vertical-align:super;\">2</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:400;\"> here. </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">Profile: </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:400;\">Select your desired routing profile. For more information about routing profiles, please visit our </span><a href=\"https://docs.anyways.eu/routing-api/\"><span style=\" font-family:\'MS Shell Dlg 2\'; text-decoration: underline; color:#0000ff;\">documentation website</span></a><span style=\" font-family:\'MS Shell Dlg 2\';\">.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">Output Folder: </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:400;\">Select the folder in which you’d like to save the routings JSON file.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">Seperate Routing: </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:400;\">Check this box if you’d like to have routing between each pair of points saved as a separate JSON file in the folder you selected above and subsequently added in QGIS as separate layers. </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">Width &amp; Color:</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:400;\"> Choose the symbology of routing layer/s in QGIS.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-weight:400;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt; text-decoration: underline;\">Origins to Destinations:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">Origins: </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:400;\">Select the layer that contains your </span><span style=\" font-family:\'MS Shell Dlg 2\';\">Origin</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:400;\"> points.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">Destinations: </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:400;\">Select the layer that contains your </span><span style=\" font-family:\'MS Shell Dlg 2\';\">Desination</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:400;\"> points.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">Instance: </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:400;\">Insert your ShortCut instance</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:400; vertical-align:super;\">2</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:400;\"> here.</span><span style=\" font-family:\'MS Shell Dlg 2\';\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">Profile: </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:400;\">Select your desired routing profile. For more information about routing profiles, please visit our </span><a href=\"https://docs.anyways.eu/routing-api/\"><span style=\" font-family:\'MS Shell Dlg 2\'; text-decoration: underline; color:#0000ff;\">documentation website</span></a><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:400;\">.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">Output Folder: </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:400;\">Select the folder in which you’d like to save the routings JSON file.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">Seperate Routing: </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:400;\">Check this box if you’d like to have routing between each pair of points saved as a separate JSON file in the folder you selected above and subsequently added in QGIS as separate layers. </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">Width &amp; Color: </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:400;\">Choose the symbology of routing layer/s in QGIS.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-weight:400;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400;\">1. Please be advised that you will need </span><a href=\"https://www.anyways.eu/shortcut.html\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:400; text-decoration: underline; color:#0000ff;\">ShortCut</span></a><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400;\"> to create scenarios. You can request a free trial version </span><a href=\"https://www.anyways.eu/contact.html\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:400; text-decoration: underline; color:#0000ff;\">here</span></a><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400;\">. </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400;\">2. Your ShortCut instance is the “</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; color:#ff0000;\">XXXX</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400;\">” part of the link that you’ll receive from us upon subscription as shown below:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; color:#0000ff;\">https ://www .anyways .eu/shortcut/</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; color:#ff0000;\">XXXX</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-weight:400;\"><br /></p></body></html>"))
        self.label_31.setText(_translate("APIRequestDialogBase", "<html><head/><body><p>Output folder <span style=\" color:#ff0000;\">*</span></p></body></html>"))
        self.shortcutTab1_widthNum.setSuffix(_translate("APIRequestDialogBase", " mm"))
        self.label_34.setText(_translate("APIRequestDialogBase", "Width"))
        self.shortcutTab1_SepRoutes_Cbx.setText(_translate("APIRequestDialogBase", "Seperate Routings"))
        self.shortcutTab1_OutDirBtn.setText(_translate("APIRequestDialogBase", "..."))
        self.label_8.setText(_translate("APIRequestDialogBase", "Client"))
        self.label_3.setText(_translate("APIRequestDialogBase", "Network"))
        self.label_7.setText(_translate("APIRequestDialogBase", "<html><head/><body><p>Points of Interest (POIs) <span style=\" color:#ff0000;\">*</span></p></body></html>"))
        self.shortcutTab1_profileCbx.setToolTip(_translate("APIRequestDialogBase", "Mode of travel"))
        self.shortcutTab1_profileCbx.setItemText(0, _translate("APIRequestDialogBase", "bicycle.fastest"))
        self.shortcutTab1_profileCbx.setItemText(1, _translate("APIRequestDialogBase", "bicycle.shortest"))
        self.shortcutTab1_profileCbx.setItemText(2, _translate("APIRequestDialogBase", "bicycle.networks"))
        self.shortcutTab1_profileCbx.setItemText(3, _translate("APIRequestDialogBase", "car"))
        self.shortcutTab1_profileCbx.setItemText(4, _translate("APIRequestDialogBase", "car.shortest"))
        self.shortcutTab1_profileCbx.setItemText(5, _translate("APIRequestDialogBase", "car.classifications"))
        self.shortcutTab1_profileCbx.setItemText(6, _translate("APIRequestDialogBase", "pedestrian.shortest"))
        self.label_33.setText(_translate("APIRequestDialogBase", "Color"))
        self.label_9.setText(_translate("APIRequestDialogBase", "Instance"))
        self.label_32.setText(_translate("APIRequestDialogBase", "<html><head/><body><p>Profile <span style=\" color:#ff0000;\">*</span></p></body></html>"))
        self.shortcutTab1_InstanceCbx.setItemText(0, _translate("APIRequestDialogBase", "0"))
        self.shortcutTab1_InstanceCbx.setItemText(1, _translate("APIRequestDialogBase", "1"))
        self.shortcutTab1_InstanceCbx.setItemText(2, _translate("APIRequestDialogBase", "2"))
        self.shortcutTab1_InstanceCbx.setItemText(3, _translate("APIRequestDialogBase", "3"))
        self.shortcutTab1_InstanceCbx.setItemText(4, _translate("APIRequestDialogBase", "4"))
        self.shortcutTab1_InstanceCbx.setItemText(5, _translate("APIRequestDialogBase", "5"))
        self.shortcutTab1_InstanceCbx.setItemText(6, _translate("APIRequestDialogBase", "6"))
        self.shortcutTab1_InstanceCbx.setItemText(7, _translate("APIRequestDialogBase", "7"))
        self.shortcutTab1_InstanceCbx.setItemText(8, _translate("APIRequestDialogBase", "8"))
        self.shortcutTab1_InstanceCbx.setItemText(9, _translate("APIRequestDialogBase", "9"))
        self.shortcutWgt.setTabText(self.shortcutWgt.indexOf(self.shortcutTab1), _translate("APIRequestDialogBase", "All POIs"))
        self.shortcutTab_2.setToolTip(_translate("APIRequestDialogBase", "Connecting all Origins to all Destinations"))
        self.shortcutTab2_OutDirBtn.setText(_translate("APIRequestDialogBase", "..."))
        self.shortcutTab2_profileCbx.setToolTip(_translate("APIRequestDialogBase", "Mode of travel"))
        self.shortcutTab2_profileCbx.setItemText(0, _translate("APIRequestDialogBase", "bicycle.fastest"))
        self.shortcutTab2_profileCbx.setItemText(1, _translate("APIRequestDialogBase", "bicycle.shortest"))
        self.shortcutTab2_profileCbx.setItemText(2, _translate("APIRequestDialogBase", "bicycle.networks"))
        self.shortcutTab2_profileCbx.setItemText(3, _translate("APIRequestDialogBase", "car"))
        self.shortcutTab2_profileCbx.setItemText(4, _translate("APIRequestDialogBase", "car.shortest"))
        self.shortcutTab2_profileCbx.setItemText(5, _translate("APIRequestDialogBase", "car.classifications"))
        self.shortcutTab2_profileCbx.setItemText(6, _translate("APIRequestDialogBase", "pedestrian.shortest"))
        self.label_38.setText(_translate("APIRequestDialogBase", "<html><head/><body><p>Origins <span style=\" color:#ff0000;\">*</span></p></body></html>"))
        self.label_39.setText(_translate("APIRequestDialogBase", "Width"))
        self.label_37.setText(_translate("APIRequestDialogBase", "<html><head/><body><p>Profile <span style=\" color:#ff0000;\">*</span></p></body></html>"))
        self.label_36.setText(_translate("APIRequestDialogBase", "Color"))
        self.label_40.setText(_translate("APIRequestDialogBase", "<html><head/><body><p>Output folder <span style=\" color:#ff0000;\">*</span></p></body></html>"))
        self.shortcutTab2_SepRoutes_Cbx.setText(_translate("APIRequestDialogBase", "Seperate Routings"))
        self.label_10.setText(_translate("APIRequestDialogBase", "Client"))
        self.label_35.setText(_translate("APIRequestDialogBase", "<html><head/><body><p>Destinations <span style=\" color:#ff0000;\">*</span></p></body></html>"))
        self.label_5.setText(_translate("APIRequestDialogBase", "Network"))
        self.shortcutTab2_widthNum.setSuffix(_translate("APIRequestDialogBase", " mm"))
        self.label_11.setText(_translate("APIRequestDialogBase", "Instance"))
        self.shortcutTab2_InstanceCbx.setItemText(0, _translate("APIRequestDialogBase", "0"))
        self.shortcutTab2_InstanceCbx.setItemText(1, _translate("APIRequestDialogBase", "1"))
        self.shortcutTab2_InstanceCbx.setItemText(2, _translate("APIRequestDialogBase", "2"))
        self.shortcutTab2_InstanceCbx.setItemText(3, _translate("APIRequestDialogBase", "3"))
        self.shortcutTab2_InstanceCbx.setItemText(4, _translate("APIRequestDialogBase", "4"))
        self.shortcutTab2_InstanceCbx.setItemText(5, _translate("APIRequestDialogBase", "5"))
        self.shortcutTab2_InstanceCbx.setItemText(6, _translate("APIRequestDialogBase", "6"))
        self.shortcutTab2_InstanceCbx.setItemText(7, _translate("APIRequestDialogBase", "7"))
        self.shortcutTab2_InstanceCbx.setItemText(8, _translate("APIRequestDialogBase", "8"))
        self.shortcutTab2_InstanceCbx.setItemText(9, _translate("APIRequestDialogBase", "9"))
        self.shortcutWgt.setTabText(self.shortcutWgt.indexOf(self.shortcutTab_2), _translate("APIRequestDialogBase", "Origins to Destinations"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.shortcutTab), _translate("APIRequestDialogBase", "ShortCut API"))
        self.label.setText(_translate("APIRequestDialogBase", "<html><head/><body><p><span style=\" color:#ffaa00;\">ANYWAYS</span> Impact Management &amp; Analysis ToolBox</p></body></html>"))

from qgscolorbutton import QgsColorButton
from qgsmaplayercombobox import QgsMapLayerComboBox
