# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ImPact_toolbox_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_APIRequestDialogBase(object):
    def setupUi(self, APIRequestDialogBase):
        APIRequestDialogBase.setObjectName("APIRequestDialogBase")
        APIRequestDialogBase.setEnabled(True)
        APIRequestDialogBase.resize(1213, 806)
        APIRequestDialogBase.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        APIRequestDialogBase.setStyleSheet("")
        APIRequestDialogBase.setSizeGripEnabled(False)
        APIRequestDialogBase.setModal(False)
        self.label_anyways_header = QtWidgets.QLabel(APIRequestDialogBase)
        self.label_anyways_header.setGeometry(QtCore.QRect(20, 760, 501, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_anyways_header.setFont(font)
        self.label_anyways_header.setObjectName("label_anyways_header")
        self.main_tab = QtWidgets.QTabWidget(APIRequestDialogBase)
        self.main_tab.setGeometry(QtCore.QRect(10, 10, 1191, 721))
        self.main_tab.setObjectName("main_tab")
        self.settings_tab = QtWidgets.QWidget()
        self.settings_tab.setObjectName("settings_tab")
        self.formLayoutWidget = QtWidgets.QWidget(self.settings_tab)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 1151, 661))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.settings_form = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.settings_form.setContentsMargins(0, 0, 0, 0)
        self.settings_form.setObjectName("settings_form")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.settings_form.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.api_key_field = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.api_key_field.setObjectName("api_key_field")
        self.settings_form.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.api_key_field)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.settings_form.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.settings_form.setItem(3, QtWidgets.QFormLayout.FieldRole, spacerItem)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.settings_form.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.label_5)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.settings_form.setItem(12, QtWidgets.QFormLayout.FieldRole, spacerItem1)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.settings_form.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.project_directory = gui.QgsFileWidget(self.formLayoutWidget)
        self.project_directory.setObjectName("project_directory")
        self.settings_form.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.project_directory)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setScaledContents(False)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.settings_form.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.label_6)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.settings_form.setItem(15, QtWidgets.QFormLayout.FieldRole, spacerItem2)
        self.impact_instance_selector = QtWidgets.QComboBox(self.formLayoutWidget)
        self.impact_instance_selector.setObjectName("impact_instance_selector")
        self.settings_form.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.impact_instance_selector)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.settings_form.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.save_settings_button = QtWidgets.QPushButton(self.formLayoutWidget)
        self.save_settings_button.setObjectName("save_settings_button")
        self.settings_form.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.save_settings_button)
        self.save_area_outline = QtWidgets.QPushButton(self.formLayoutWidget)
        self.save_area_outline.setObjectName("save_area_outline")
        self.settings_form.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.save_area_outline)
        self.impact_url_textfield = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.impact_url_textfield.setObjectName("impact_url_textfield")
        self.settings_form.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.impact_url_textfield)
        self.save_impact_url_button = QtWidgets.QPushButton(self.formLayoutWidget)
        self.save_impact_url_button.setObjectName("save_impact_url_button")
        self.settings_form.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.save_impact_url_button)
        self.label.raise_()
        self.api_key_field.raise_()
        self.label_2.raise_()
        self.label_5.raise_()
        self.label_4.raise_()
        self.project_directory.raise_()
        self.label_6.raise_()
        self.impact_instance_selector.raise_()
        self.label_3.raise_()
        self.save_settings_button.raise_()
        self.save_area_outline.raise_()
        self.save_impact_url_button.raise_()
        self.impact_url_textfield.raise_()
        self.main_tab.addTab(self.settings_tab, "")
        self.movement_pairs_tab = QtWidgets.QWidget()
        self.movement_pairs_tab.setObjectName("movement_pairs_tab")
        self.formLayoutWidget_5 = QtWidgets.QWidget(self.movement_pairs_tab)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(10, 0, 1131, 661))
        self.formLayoutWidget_5.setObjectName("formLayoutWidget_5")
        self.movement_pairs_form = QtWidgets.QFormLayout(self.formLayoutWidget_5)
        self.movement_pairs_form.setContentsMargins(0, 0, 0, 0)
        self.movement_pairs_form.setObjectName("movement_pairs_form")
        self.label_19 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_19.setWordWrap(True)
        self.label_19.setObjectName("label_19")
        self.movement_pairs_form.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_19)
        self.label_20 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.movement_pairs_form.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.label_20)
        self.home_locations = gui.QgsMapLayerComboBox(self.formLayoutWidget_5)
        self.home_locations.setObjectName("home_locations")
        self.movement_pairs_form.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.home_locations)
        self.label_21 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_21.setObjectName("label_21")
        self.movement_pairs_form.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.label_22 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_22.setWordWrap(True)
        self.label_22.setObjectName("label_22")
        self.movement_pairs_form.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_22)
        self.work_locations = gui.QgsMapLayerComboBox(self.formLayoutWidget_5)
        self.work_locations.setObjectName("work_locations")
        self.movement_pairs_form.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.work_locations)
        self.label_23 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_23.setObjectName("label_23")
        self.movement_pairs_form.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.label_24 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_24.setObjectName("label_24")
        self.movement_pairs_form.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.label_24)
        self.include_cyclists = QtWidgets.QCheckBox(self.formLayoutWidget_5)
        self.include_cyclists.setObjectName("include_cyclists")
        self.movement_pairs_form.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.include_cyclists)
        self.include_car = QtWidgets.QCheckBox(self.formLayoutWidget_5)
        self.include_car.setObjectName("include_car")
        self.movement_pairs_form.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.include_car)
        self.include_train = QtWidgets.QCheckBox(self.formLayoutWidget_5)
        self.include_train.setObjectName("include_train")
        self.movement_pairs_form.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.include_train)
        self.include_public_transport = QtWidgets.QCheckBox(self.formLayoutWidget_5)
        self.include_public_transport.setObjectName("include_public_transport")
        self.movement_pairs_form.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.include_public_transport)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.movement_pairs_form.setItem(8, QtWidgets.QFormLayout.FieldRole, spacerItem3)
        self.label_25 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_25.setObjectName("label_25")
        self.movement_pairs_form.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.label_27 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_27.setWordWrap(True)
        self.label_27.setObjectName("label_27")
        self.movement_pairs_form.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_27)
        self.label_28 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_28.setWordWrap(True)
        self.label_28.setObjectName("label_28")
        self.movement_pairs_form.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.label_28)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.movement_pairs_form.setItem(13, QtWidgets.QFormLayout.FieldRole, spacerItem4)
        self.query_movement_pairs_button = QtWidgets.QPushButton(self.formLayoutWidget_5)
        self.query_movement_pairs_button.setObjectName("query_movement_pairs_button")
        self.movement_pairs_form.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.query_movement_pairs_button)
        self.main_tab.addTab(self.movement_pairs_tab, "")
        self.routeplanning_tab = QtWidgets.QWidget()
        self.routeplanning_tab.setObjectName("routeplanning_tab")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.routeplanning_tab)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(0, 20, 1181, 591))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.routeplanning_form = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.routeplanning_form.setContentsMargins(0, 0, 0, 0)
        self.routeplanning_form.setObjectName("routeplanning_form")
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.routeplanning_form.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_15)
        self.label_29 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_29.setObjectName("label_29")
        self.routeplanning_form.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_29)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.routeplanning_form.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.scenario_picker = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.scenario_picker.setEditable(False)
        self.scenario_picker.setCurrentText("")
        self.scenario_picker.setObjectName("scenario_picker")
        self.routeplanning_form.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.scenario_picker)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.routeplanning_form.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.label_8)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.routeplanning_form.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.profile_picker = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.profile_picker.setObjectName("profile_picker")
        self.routeplanning_form.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.profile_picker)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.routeplanning_form.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.label_10)
        self.profile_explanation = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.profile_explanation.setFont(font)
        self.profile_explanation.setObjectName("profile_explanation")
        self.routeplanning_form.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.profile_explanation)
        self.toolbox_origin_destination_or_movement = QtWidgets.QTabWidget(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolbox_origin_destination_or_movement.sizePolicy().hasHeightForWidth())
        self.toolbox_origin_destination_or_movement.setSizePolicy(sizePolicy)
        self.toolbox_origin_destination_or_movement.setMinimumSize(QtCore.QSize(0, 210))
        self.toolbox_origin_destination_or_movement.setObjectName("toolbox_origin_destination_or_movement")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.tab1)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(0, 10, 1091, 161))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_11.setObjectName("label_11")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.departure_layer_picker = gui.QgsMapLayerComboBox(self.formLayoutWidget_4)
        self.departure_layer_picker.setObjectName("departure_layer_picker")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.departure_layer_picker)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_12.setObjectName("label_12")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_12)
        self.arrival_layer_picker = gui.QgsMapLayerComboBox(self.formLayoutWidget_4)
        self.arrival_layer_picker.setObjectName("arrival_layer_picker")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.arrival_layer_picker)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_13.setObjectName("label_13")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_14.setObjectName("label_14")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_14)
        self.toolbox_origin_destination_or_movement.addTab(self.tab1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.tab_2)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(0, 10, 1141, 131))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.movement_pairs_layer_picker = gui.QgsMapLayerComboBox(self.formLayoutWidget_3)
        self.movement_pairs_layer_picker.setObjectName("movement_pairs_layer_picker")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.movement_pairs_layer_picker)
        self.label_17 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_17.setObjectName("label_17")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.label_18 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_18.setWordWrap(True)
        self.label_18.setObjectName("label_18")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_18)
        self.toolbox_origin_destination_or_movement.addTab(self.tab_2, "")
        self.routeplanning_form.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.toolbox_origin_destination_or_movement)
        self.label_16 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.routeplanning_form.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.label_16)
        self.perform_routeplanning_button = QtWidgets.QPushButton(self.routeplanning_tab)
        self.perform_routeplanning_button.setGeometry(QtCore.QRect(730, 620, 441, 51))
        self.perform_routeplanning_button.setObjectName("perform_routeplanning_button")
        self.main_tab.addTab(self.routeplanning_tab, "")
        self.traffic_diff_tab = QtWidgets.QWidget()
        self.traffic_diff_tab.setObjectName("traffic_diff_tab")
        self.formLayoutWidget_6 = QtWidgets.QWidget(self.traffic_diff_tab)
        self.formLayoutWidget_6.setGeometry(QtCore.QRect(10, 10, 1171, 641))
        self.formLayoutWidget_6.setObjectName("formLayoutWidget_6")
        self.traffic_diff_form = QtWidgets.QFormLayout(self.formLayoutWidget_6)
        self.traffic_diff_form.setContentsMargins(0, 0, 0, 0)
        self.traffic_diff_form.setObjectName("traffic_diff_form")
        self.zero_situation_picker = gui.QgsMapLayerComboBox(self.formLayoutWidget_6)
        self.zero_situation_picker.setObjectName("zero_situation_picker")
        self.traffic_diff_form.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.zero_situation_picker)
        self.label_30 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.label_30.setObjectName("label_30")
        self.traffic_diff_form.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.label_31 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.label_31.setObjectName("label_31")
        self.traffic_diff_form.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_31)
        self.label_32 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.label_32.setWordWrap(True)
        self.label_32.setObjectName("label_32")
        self.traffic_diff_form.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_32)
        self.new_situation_picker = gui.QgsMapLayerComboBox(self.formLayoutWidget_6)
        self.new_situation_picker.setObjectName("new_situation_picker")
        self.traffic_diff_form.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.new_situation_picker)
        self.label_33 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.label_33.setObjectName("label_33")
        self.traffic_diff_form.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_33)
        self.label_34 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.label_34.setObjectName("label_34")
        self.traffic_diff_form.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.label_34)
        self.calculate_traffic_shift_button = QtWidgets.QPushButton(self.formLayoutWidget_6)
        self.calculate_traffic_shift_button.setObjectName("calculate_traffic_shift_button")
        self.traffic_diff_form.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.calculate_traffic_shift_button)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.traffic_diff_form.setItem(5, QtWidgets.QFormLayout.FieldRole, spacerItem5)
        self.main_tab.addTab(self.traffic_diff_tab, "")

        self.retranslateUi(APIRequestDialogBase)
        self.main_tab.setCurrentIndex(0)
        self.toolbox_origin_destination_or_movement.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(APIRequestDialogBase)

    def retranslateUi(self, APIRequestDialogBase):
        _translate = QtCore.QCoreApplication.translate
        APIRequestDialogBase.setWindowTitle(_translate("APIRequestDialogBase", "ImPact ToolBox"))
        self.label_anyways_header.setText(_translate("APIRequestDialogBase", "<html><head/><body><p><span style=\" color:#ffaa00;\">ANYWAYS</span>\n"
"                    Impact Management &amp; Analysis ToolBox</p></body></html>\n"
"                "))
        self.label.setText(_translate("APIRequestDialogBase", "Api-Key"))
        self.label_2.setText(_translate("APIRequestDialogBase", "A personal string which acts as key, provided to you by ANYWAYS BV."))
        self.label_5.setText(_translate("APIRequestDialogBase", "The URL of one of your impact instances. Copy and paste the URL of any\n"
"                                        instance here, the tool will figure out which instances exist. You can pick any\n"
"                                        later on\n"
"                                    "))
        self.label_4.setText(_translate("APIRequestDialogBase", "Project directory"))
        self.label_6.setText(_translate("APIRequestDialogBase", "This is the path of the current project. All intermediate files (output from\n"
"                                        routeplanning, ...) will be saved here as geoJson.\n"
"                                    "))
        self.label_3.setText(_translate("APIRequestDialogBase", "ImPact URL"))
        self.save_settings_button.setText(_translate("APIRequestDialogBase", "Save settings"))
        self.save_area_outline.setText(_translate("APIRequestDialogBase", "Save the outline of this Impact instance as a layer"))
        self.save_impact_url_button.setText(_translate("APIRequestDialogBase", "Save impact instance"))
        self.main_tab.setTabText(self.main_tab.indexOf(self.settings_tab), _translate("APIRequestDialogBase", "Settings"))
        self.label_19.setText(_translate("APIRequestDialogBase", "The FOD Mobiliteit did a survey in 2017 collecting how people moved from\n"
"                                        their home to their work. This open data set can be queried to construct a\n"
"                                        movement pair layer.\n"
"                                    "))
        self.label_21.setText(_translate("APIRequestDialogBase", "Home area"))
        self.label_22.setText(_translate("APIRequestDialogBase", "A polygon marking the boundaries where the commuters live. Note that all\n"
"                                        commuters are bundled to the centerpoint of the municipality\n"
"                                    "))
        self.label_23.setText(_translate("APIRequestDialogBase", "Work locations"))
        self.label_24.setText(_translate("APIRequestDialogBase", "The locations where the commuters work"))
        self.include_cyclists.setText(_translate("APIRequestDialogBase", "Include cyclist counts"))
        self.include_car.setText(_translate("APIRequestDialogBase", "Include car counts"))
        self.include_train.setText(_translate("APIRequestDialogBase", "Include train counts"))
        self.include_public_transport.setText(_translate("APIRequestDialogBase", "Include public transport counts"))
        self.label_25.setText(_translate("APIRequestDialogBase", "Transport modes to count"))
        self.label_27.setText(_translate("APIRequestDialogBase", "Make sure this area is big enough. Only works in Belgium"))
        self.label_28.setText(_translate("APIRequestDialogBase", "Make sure this area is big enough. Only works in Belgium; can be the same as\n"
"                                        locations of departure\n"
"                                    "))
        self.query_movement_pairs_button.setText(_translate("APIRequestDialogBase", "Query movement pairs"))
        self.main_tab.setTabText(self.main_tab.indexOf(self.movement_pairs_tab), _translate("APIRequestDialogBase", "Load movement pairs"))
        self.label_15.setText(_translate("APIRequestDialogBase", "Calculate routes between multiple departure points and multiple arrival\n"
"                                        points\n"
"                                    "))
        self.label_29.setText(_translate("APIRequestDialogBase", "All individual road segments will be grouped and counted"))
        self.label_7.setText(_translate("APIRequestDialogBase", "Scenario"))
        self.label_8.setText(_translate("APIRequestDialogBase", "Use real-life routeplanning or a scenario from your ImPact instance"))
        self.label_9.setText(_translate("APIRequestDialogBase", "Profile"))
        self.label_10.setText(_translate("APIRequestDialogBase", "Select which vehicle to plan and it behaves. Read below how the profile\n"
"                                        behaves\n"
"                                    "))
        self.profile_explanation.setText(_translate("APIRequestDialogBase", "(Select a profile first. The profile info will be shown here)"))
        self.label_11.setText(_translate("APIRequestDialogBase", "Departure"))
        self.label_12.setText(_translate("APIRequestDialogBase", "Every point in this layer will be considered a departure\n"
"                                                            point\n"
"                                                        "))
        self.label_13.setText(_translate("APIRequestDialogBase", "Arrival"))
        self.label_14.setText(_translate("APIRequestDialogBase", "Every point in this layer will be used as arrival point.\n"
"                                                            To do matrix routing, select the same as departure\n"
"                                                        "))
        self.toolbox_origin_destination_or_movement.setTabText(self.toolbox_origin_destination_or_movement.indexOf(self.tab1), _translate("APIRequestDialogBase", "Plan routes between point layers"))
        self.label_17.setText(_translate("APIRequestDialogBase", "Select a movement layer"))
        self.label_18.setText(_translate("APIRequestDialogBase", "Use a layer with movement data (e.g. loaded from file or\n"
"                                                            from the FOD). Routeplanning will be performed on every\n"
"                                                            origin-destination pair, which will be weighted\n"
"                                                        "))
        self.toolbox_origin_destination_or_movement.setTabText(self.toolbox_origin_destination_or_movement.indexOf(self.tab_2), _translate("APIRequestDialogBase", "Plan routes over a linestring layer"))
        self.perform_routeplanning_button.setText(_translate("APIRequestDialogBase", "Perform routeplanning"))
        self.main_tab.setTabText(self.main_tab.indexOf(self.routeplanning_tab), _translate("APIRequestDialogBase", "Routeplanning"))
        self.label_30.setText(_translate("APIRequestDialogBase", "Zero situation"))
        self.label_31.setText(_translate("APIRequestDialogBase", "The weighted segment layer of the original, zero situation."))
        self.label_32.setText(_translate("APIRequestDialogBase", "Compare two layers of weighted segments to calculate a traffic shift. These\n"
"                                        can be constructed in the routeplanning tab\n"
"                                    "))
        self.label_33.setText(_translate("APIRequestDialogBase", "New situation"))
        self.label_34.setText(_translate("APIRequestDialogBase", "The weighted segment layer of the new (hypothetical) situation."))
        self.calculate_traffic_shift_button.setText(_translate("APIRequestDialogBase", "Calculate traffic shift"))
        self.main_tab.setTabText(self.main_tab.indexOf(self.traffic_diff_tab), _translate("APIRequestDialogBase", "Calculate traffic differences"))
from qgis import gui
