# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ImPact_toolbox_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_APIRequestDialogBase(object):
    def setupUi(self, APIRequestDialogBase):
        APIRequestDialogBase.setObjectName("APIRequestDialogBase")
        APIRequestDialogBase.setEnabled(True)
        APIRequestDialogBase.resize(671, 767)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(APIRequestDialogBase.sizePolicy().hasHeightForWidth())
        APIRequestDialogBase.setSizePolicy(sizePolicy)
        APIRequestDialogBase.setMaximumSize(QtCore.QSize(16777215, 16777215))
        APIRequestDialogBase.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        APIRequestDialogBase.setWindowIcon(icon)
        APIRequestDialogBase.setStyleSheet("")
        APIRequestDialogBase.setSizeGripEnabled(False)
        APIRequestDialogBase.setModal(False)
        self.gridLayout_6 = QtWidgets.QGridLayout(APIRequestDialogBase)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.toolBox = QtWidgets.QToolBox(APIRequestDialogBase)
        self.toolBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.toolBox.setFont(font)
        self.toolBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.toolBox.setAcceptDrops(False)
        self.toolBox.setAutoFillBackground(False)
        self.toolBox.setStyleSheet("")
        self.toolBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.toolBox.setFrameShadow(QtWidgets.QFrame.Plain)
        self.toolBox.setLineWidth(1)
        self.toolBox.setMidLineWidth(10)
        self.toolBox.setObjectName("toolBox")
        self.routingTab = QtWidgets.QWidget()
        self.routingTab.setGeometry(QtCore.QRect(0, 0, 647, 643))
        self.routingTab.setObjectName("routingTab")
        self.routingWgt = QtWidgets.QTabWidget(self.routingTab)
        self.routingWgt.setGeometry(QtCore.QRect(11, 58, 631, 551))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.routingWgt.sizePolicy().hasHeightForWidth())
        self.routingWgt.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.routingWgt.setFont(font)
        self.routingWgt.setFocusPolicy(QtCore.Qt.TabFocus)
        self.routingWgt.setToolTip("")
        self.routingWgt.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.routingWgt.setObjectName("routingWgt")
        self.routingTab1 = QtWidgets.QWidget()
        self.routingTab1.setObjectName("routingTab1")
        self.routingtab1_SepRoutes_Cbx = QtWidgets.QCheckBox(self.routingTab1)
        self.routingtab1_SepRoutes_Cbx.setGeometry(QtCore.QRect(14, 124, 132, 20))
        self.routingtab1_SepRoutes_Cbx.setObjectName("routingtab1_SepRoutes_Cbx")
        self.routingTab1_widthNum = QtWidgets.QSpinBox(self.routingTab1)
        self.routingTab1_widthNum.setGeometry(QtCore.QRect(170, 151, 68, 22))
        self.routingTab1_widthNum.setMinimum(1)
        self.routingTab1_widthNum.setMaximum(10)
        self.routingTab1_widthNum.setObjectName("routingTab1_widthNum")
        self.label_21 = QtWidgets.QLabel(self.routingTab1)
        self.label_21.setGeometry(QtCore.QRect(10, 90, 87, 16))
        self.label_21.setObjectName("label_21")
        self.routingTab1_outDirTxt = QtWidgets.QLineEdit(self.routingTab1)
        self.routingTab1_outDirTxt.setGeometry(QtCore.QRect(255, 92, 371, 22))
        self.routingTab1_outDirTxt.setText("")
        self.routingTab1_outDirTxt.setReadOnly(True)
        self.routingTab1_outDirTxt.setObjectName("routingTab1_outDirTxt")
        self.routingTab1_mLayers = QgsMapLayerComboBox(self.routingTab1)
        self.routingTab1_mLayers.setEnabled(True)
        self.routingTab1_mLayers.setGeometry(QtCore.QRect(252, 11, 371, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.routingTab1_mLayers.sizePolicy().hasHeightForWidth())
        self.routingTab1_mLayers.setSizePolicy(sizePolicy)
        self.routingTab1_mLayers.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.routingTab1_mLayers.setObjectName("routingTab1_mLayers")
        self.routingTab1_profileCbx = QtWidgets.QComboBox(self.routingTab1)
        self.routingTab1_profileCbx.setGeometry(QtCore.QRect(252, 40, 371, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.routingTab1_profileCbx.sizePolicy().hasHeightForWidth())
        self.routingTab1_profileCbx.setSizePolicy(sizePolicy)
        self.routingTab1_profileCbx.setEditable(True)
        self.routingTab1_profileCbx.setObjectName("routingTab1_profileCbx")
        self.routingTab1_profileCbx.addItem("")
        self.routingTab1_profileCbx.setItemText(0, "")
        self.routingTab1_profileCbx.addItem("")
        self.routingTab1_profileCbx.addItem("")
        self.routingTab1_profileCbx.addItem("")
        self.routingTab1_profileCbx.addItem("")
        self.routingTab1_profileCbx.addItem("")
        self.routingTab1_profileCbx.addItem("")
        self.routingTab1_profileCbx.addItem("")
        self.label_6 = QtWidgets.QLabel(self.routingTab1)
        self.label_6.setGeometry(QtCore.QRect(11, 11, 149, 16))
        self.label_6.setObjectName("label_6")
        self.routingTab1_OutDirBtn = QtWidgets.QPushButton(self.routingTab1)
        self.routingTab1_OutDirBtn.setGeometry(QtCore.QRect(170, 89, 30, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.routingTab1_OutDirBtn.sizePolicy().hasHeightForWidth())
        self.routingTab1_OutDirBtn.setSizePolicy(sizePolicy)
        self.routingTab1_OutDirBtn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.routingTab1_OutDirBtn.setObjectName("routingTab1_OutDirBtn")
        self.label_22 = QtWidgets.QLabel(self.routingTab1)
        self.label_22.setGeometry(QtCore.QRect(10, 40, 48, 16))
        self.label_22.setObjectName("label_22")
        self.label_24 = QtWidgets.QLabel(self.routingTab1)
        self.label_24.setGeometry(QtCore.QRect(14, 180, 30, 16))
        self.label_24.setObjectName("label_24")
        self.label_23 = QtWidgets.QLabel(self.routingTab1)
        self.label_23.setGeometry(QtCore.QRect(14, 151, 33, 16))
        self.label_23.setObjectName("label_23")
        self.routingTab1_mColorBtn = QgsColorButton(self.routingTab1)
        self.routingTab1_mColorBtn.setGeometry(QtCore.QRect(170, 180, 71, 26))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.routingTab1_mColorBtn.sizePolicy().hasHeightForWidth())
        self.routingTab1_mColorBtn.setSizePolicy(sizePolicy)
        self.routingTab1_mColorBtn.setMouseTracking(False)
        self.routingTab1_mColorBtn.setObjectName("routingTab1_mColorBtn")
        self.label_31 = QtWidgets.QLabel(self.routingTab1)
        self.label_31.setGeometry(QtCore.QRect(10, 60, 291, 16))
        self.label_31.setOpenExternalLinks(True)
        self.label_31.setObjectName("label_31")
        self.routingWgt.addTab(self.routingTab1, "")
        self.routingTab2 = QtWidgets.QWidget()
        self.routingTab2.setObjectName("routingTab2")
        self.label_27 = QtWidgets.QLabel(self.routingTab2)
        self.label_27.setGeometry(QtCore.QRect(10, 121, 87, 16))
        self.label_27.setObjectName("label_27")
        self.routingTab2_O_mLayers = QgsMapLayerComboBox(self.routingTab2)
        self.routingTab2_O_mLayers.setGeometry(QtCore.QRect(250, 10, 371, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.routingTab2_O_mLayers.sizePolicy().hasHeightForWidth())
        self.routingTab2_O_mLayers.setSizePolicy(sizePolicy)
        self.routingTab2_O_mLayers.setObjectName("routingTab2_O_mLayers")
        self.label_26 = QtWidgets.QLabel(self.routingTab2)
        self.label_26.setGeometry(QtCore.QRect(10, 70, 48, 16))
        self.label_26.setObjectName("label_26")
        self.routingTab2_profileCbx = QtWidgets.QComboBox(self.routingTab2)
        self.routingTab2_profileCbx.setGeometry(QtCore.QRect(250, 70, 371, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.routingTab2_profileCbx.sizePolicy().hasHeightForWidth())
        self.routingTab2_profileCbx.setSizePolicy(sizePolicy)
        self.routingTab2_profileCbx.setEditable(True)
        self.routingTab2_profileCbx.setObjectName("routingTab2_profileCbx")
        self.routingTab2_profileCbx.addItem("")
        self.routingTab2_profileCbx.setItemText(0, "")
        self.routingTab2_profileCbx.addItem("")
        self.routingTab2_profileCbx.addItem("")
        self.routingTab2_profileCbx.addItem("")
        self.routingTab2_profileCbx.addItem("")
        self.routingTab2_profileCbx.addItem("")
        self.routingTab2_profileCbx.addItem("")
        self.routingTab2_profileCbx.addItem("")
        self.routingTab2_OutDirBtn = QtWidgets.QPushButton(self.routingTab2)
        self.routingTab2_OutDirBtn.setGeometry(QtCore.QRect(160, 121, 30, 28))
        self.routingTab2_OutDirBtn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.routingTab2_OutDirBtn.setObjectName("routingTab2_OutDirBtn")
        self.routingTab2_widthNum = QtWidgets.QSpinBox(self.routingTab2)
        self.routingTab2_widthNum.setGeometry(QtCore.QRect(150, 181, 71, 22))
        self.routingTab2_widthNum.setMinimum(1)
        self.routingTab2_widthNum.setMaximum(10)
        self.routingTab2_widthNum.setObjectName("routingTab2_widthNum")
        self.label_29 = QtWidgets.QLabel(self.routingTab2)
        self.label_29.setGeometry(QtCore.QRect(11, 210, 30, 16))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.routingTab2)
        self.label_30.setGeometry(QtCore.QRect(11, 181, 33, 16))
        self.label_30.setObjectName("label_30")
        self.label_28 = QtWidgets.QLabel(self.routingTab2)
        self.label_28.setGeometry(QtCore.QRect(11, 40, 81, 16))
        self.label_28.setObjectName("label_28")
        self.routingTab2_mColorBtn = QgsColorButton(self.routingTab2)
        self.routingTab2_mColorBtn.setGeometry(QtCore.QRect(150, 210, 71, 26))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.routingTab2_mColorBtn.sizePolicy().hasHeightForWidth())
        self.routingTab2_mColorBtn.setSizePolicy(sizePolicy)
        self.routingTab2_mColorBtn.setMouseTracking(False)
        self.routingTab2_mColorBtn.setObjectName("routingTab2_mColorBtn")
        self.routingTab2_D_mLayers = QgsMapLayerComboBox(self.routingTab2)
        self.routingTab2_D_mLayers.setGeometry(QtCore.QRect(250, 40, 371, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.routingTab2_D_mLayers.sizePolicy().hasHeightForWidth())
        self.routingTab2_D_mLayers.setSizePolicy(sizePolicy)
        self.routingTab2_D_mLayers.setObjectName("routingTab2_D_mLayers")
        self.label_25 = QtWidgets.QLabel(self.routingTab2)
        self.label_25.setGeometry(QtCore.QRect(11, 11, 52, 16))
        self.label_25.setObjectName("label_25")
        self.routingTab2_outDirTxt = QtWidgets.QLineEdit(self.routingTab2)
        self.routingTab2_outDirTxt.setGeometry(QtCore.QRect(250, 121, 371, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.routingTab2_outDirTxt.sizePolicy().hasHeightForWidth())
        self.routingTab2_outDirTxt.setSizePolicy(sizePolicy)
        self.routingTab2_outDirTxt.setText("")
        self.routingTab2_outDirTxt.setReadOnly(True)
        self.routingTab2_outDirTxt.setObjectName("routingTab2_outDirTxt")
        self.routingtab2_SepRoutes_Cbx = QtWidgets.QCheckBox(self.routingTab2)
        self.routingtab2_SepRoutes_Cbx.setGeometry(QtCore.QRect(11, 154, 132, 20))
        self.routingtab2_SepRoutes_Cbx.setObjectName("routingtab2_SepRoutes_Cbx")
        self.label_32 = QtWidgets.QLabel(self.routingTab2)
        self.label_32.setGeometry(QtCore.QRect(10, 90, 341, 16))
        self.label_32.setOpenExternalLinks(True)
        self.label_32.setObjectName("label_32")
        self.routingWgt.addTab(self.routingTab2, "")
        self.label_2 = QtWidgets.QLabel(self.routingTab)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 71, 18))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.routingTab_KeyHolder = QtWidgets.QLineEdit(self.routingTab)
        self.routingTab_KeyHolder.setGeometry(QtCore.QRect(100, 10, 531, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.routingTab_KeyHolder.sizePolicy().hasHeightForWidth())
        self.routingTab_KeyHolder.setSizePolicy(sizePolicy)
        self.routingTab_KeyHolder.setObjectName("routingTab_KeyHolder")
        self.label_4 = QtWidgets.QLabel(self.routingTab)
        self.label_4.setGeometry(QtCore.QRect(8, 610, 651, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.routingTab)
        self.label_5.setGeometry(QtCore.QRect(510, 610, 131, 20))
        self.label_5.setOpenExternalLinks(True)
        self.label_5.setObjectName("label_5")
        self.toolBox.addItem(self.routingTab, "")
        self.gridLayout_6.addWidget(self.toolBox, 1, 0, 1, 1)
        self.button_box = QtWidgets.QDialogButtonBox(APIRequestDialogBase)
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.gridLayout_6.addWidget(self.button_box, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(APIRequestDialogBase)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 1)

        self.retranslateUi(APIRequestDialogBase)
        self.toolBox.setCurrentIndex(0)
        self.toolBox.layout().setSpacing(10)
        self.routingWgt.setCurrentIndex(0)
        self.button_box.accepted.connect(APIRequestDialogBase.accept)
        self.button_box.rejected.connect(APIRequestDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(APIRequestDialogBase)

    def retranslateUi(self, APIRequestDialogBase):
        _translate = QtCore.QCoreApplication.translate
        APIRequestDialogBase.setWindowTitle(_translate("APIRequestDialogBase", "ImPact ToolBox"))
        self.routingtab1_SepRoutes_Cbx.setText(_translate("APIRequestDialogBase", "Seperate Routings"))
        self.routingTab1_widthNum.setSuffix(_translate("APIRequestDialogBase", " mm"))
        self.label_21.setText(_translate("APIRequestDialogBase", "<html><head/><body><p>Output folder <span style=\" color:#ff0000;\">*</span></p></body></html>"))
        self.routingTab1_profileCbx.setToolTip(_translate("APIRequestDialogBase", "Mode of travel"))
        self.routingTab1_profileCbx.setItemText(1, _translate("APIRequestDialogBase", "bicycle.fastest"))
        self.routingTab1_profileCbx.setItemText(2, _translate("APIRequestDialogBase", "bicycle.shortest"))
        self.routingTab1_profileCbx.setItemText(3, _translate("APIRequestDialogBase", "bicycle.networks"))
        self.routingTab1_profileCbx.setItemText(4, _translate("APIRequestDialogBase", "car.fastest"))
        self.routingTab1_profileCbx.setItemText(5, _translate("APIRequestDialogBase", "car.shortest"))
        self.routingTab1_profileCbx.setItemText(6, _translate("APIRequestDialogBase", "car.classifications"))
        self.routingTab1_profileCbx.setItemText(7, _translate("APIRequestDialogBase", "pedestrian.shortest"))
        self.label_6.setText(_translate("APIRequestDialogBase", "<html><head/><body><p>Points of Interest (POIs) <span style=\" color:#ff0000;\">*</span></p></body></html>"))
        self.routingTab1_OutDirBtn.setText(_translate("APIRequestDialogBase", "..."))
        self.label_22.setText(_translate("APIRequestDialogBase", "<html><head/><body><p>Profile <span style=\" color:#ff0000;\">*</span></p></body></html>"))
        self.label_24.setText(_translate("APIRequestDialogBase", "Color"))
        self.label_23.setText(_translate("APIRequestDialogBase", "Width"))
        self.label_31.setText(_translate("APIRequestDialogBase", "<html><head/><body><p><span style=\" font-size:6pt;\">For more details, please visit </span><a href=\"https://docs.anyways.eu/routing-api/\"><span style=\" text-decoration: underline; color:#0000ff;\">our documentation website</span></a></p></body></html>"))
        self.routingWgt.setTabText(self.routingWgt.indexOf(self.routingTab1), _translate("APIRequestDialogBase", "All POIs"))
        self.routingTab2.setToolTip(_translate("APIRequestDialogBase", "Connecting all Origins to all Destinations"))
        self.label_27.setText(_translate("APIRequestDialogBase", "<html><head/><body><p>Output folder <span style=\" color:#ff0000;\">*</span></p></body></html>"))
        self.label_26.setText(_translate("APIRequestDialogBase", "<html><head/><body><p>Profile <span style=\" color:#ff0000;\">*</span></p></body></html>"))
        self.routingTab2_profileCbx.setToolTip(_translate("APIRequestDialogBase", "Mode of travel"))
        self.routingTab2_profileCbx.setItemText(1, _translate("APIRequestDialogBase", "bicycle.fastest"))
        self.routingTab2_profileCbx.setItemText(2, _translate("APIRequestDialogBase", "bicycle.shortest"))
        self.routingTab2_profileCbx.setItemText(3, _translate("APIRequestDialogBase", "bicycle.networks"))
        self.routingTab2_profileCbx.setItemText(4, _translate("APIRequestDialogBase", "car.fastest"))
        self.routingTab2_profileCbx.setItemText(5, _translate("APIRequestDialogBase", "car.shortest"))
        self.routingTab2_profileCbx.setItemText(6, _translate("APIRequestDialogBase", "car.classifications"))
        self.routingTab2_profileCbx.setItemText(7, _translate("APIRequestDialogBase", "pedestrian.shortest"))
        self.routingTab2_OutDirBtn.setText(_translate("APIRequestDialogBase", "..."))
        self.routingTab2_widthNum.setSuffix(_translate("APIRequestDialogBase", " mm"))
        self.label_29.setText(_translate("APIRequestDialogBase", "Color"))
        self.label_30.setText(_translate("APIRequestDialogBase", "Width"))
        self.label_28.setText(_translate("APIRequestDialogBase", "<html><head/><body><p>Destinations <span style=\" color:#ff0000;\">*</span></p></body></html>"))
        self.label_25.setText(_translate("APIRequestDialogBase", "<html><head/><body><p>Origins <span style=\" color:#ff0000;\">*</span></p></body></html>"))
        self.routingtab2_SepRoutes_Cbx.setText(_translate("APIRequestDialogBase", "Seperate Routings"))
        self.label_32.setText(_translate("APIRequestDialogBase", "<html><head/><body><p><span style=\" font-size:6pt;\">For more details, please visit </span><a href=\"https://docs.anyways.eu/routing-api/\"><span style=\" text-decoration: underline; color:#0000ff;\">our documentation website</span></a></p></body></html>"))
        self.routingWgt.setTabText(self.routingWgt.indexOf(self.routingTab2), _translate("APIRequestDialogBase", "Origins to Destinations"))
        self.label_2.setText(_translate("APIRequestDialogBase", "<html><head/><body><p>API Key <span style=\" color:#ff0000;\">*</span></p></body></html>"))
        self.label_4.setText(_translate("APIRequestDialogBase", "<html><head/><body><p><span style=\" font-size:8pt; font-weight:400; color:#ff0000;\">*</span><span style=\" font-size:8pt; font-weight:400;\"> Indicates required field</span></p></body></html>"))
        self.label_5.setText(_translate("APIRequestDialogBase", "<html><head/><body><p><a href=\"https://www.dropbox.com/s/v9uz830djoq031a/ANYWAYS_ImPact%20Toolbox%20Manual.pdf?dl=0\"><span style=\" font-size:8pt; font-weight:400; text-decoration: underline; color:#0000ff;\">Download the manual</span></a></p></body></html>"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.routingTab), _translate("APIRequestDialogBase", "Routing API"))
        self.label.setText(_translate("APIRequestDialogBase", "<html><head/><body><p><span style=\" color:#ffaa00;\">ANYWAYS</span> Impact Management &amp; Analysis ToolBox</p></body></html>"))

from qgscolorbutton import QgsColorButton
from qgsmaplayercombobox import QgsMapLayerComboBox
