name: "build plugin"
description: "Builds the plugin and the needed resources"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - name: Install pb_tool
      shell: "bash"
      run: python -m pip install pb_tool
    - name: Compile
      shell: "bash"
      run: pb_tool compile
      
    - name: Zip
      shell: "bash"
      run: pb_tool zip
      
    - name: Read metadata.txt
      id: metadata
      uses: juliangruber/read-file-action@v1
      with:
        path: ./metadata.txt
        
    - uses: actions-ecosystem/action-regex-match@v2
      id: regex-match
      with:
        text: ${{ steps.metadata.outputs.content }}
        regex: '^version=(.*)$'
        flags: 'gm'
        
    - run: echo ${{ steps.regex-match.outputs.match }}
      shell: "bash"
    - run: echo ${{ steps.regex-match.outputs.group1 }}
      shell: "bash"
      
    - name: Copy Zip
      run: cp ./zip_build/anyways_impact_toolbox.zip anyways-impact-toolbox-${{ steps.regex-match.outputs.group1 }}.zip
      shell: "bash"

