name: staging
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: "Build"
      uses: "./.github/actions/build-plugin"
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "v${{ steps.regex-match.outputs.group1 }}-dev"
        files: |
          LICENSE
          *.zip
    - name: Publish To QGIS repo.
      run: python ./deployment/plugin_upload.py -u xivk -w ${{ secrets.QGIS_REPO_SECRET }} anyways-impact-toolbox-${{ steps.regex-match.outputs.group1 }}.zip
