name: production
on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: "Build"
      uses: "./.github/actions/build-plugin"
    - name: "Print zip name"
      run: "echo 'If this were production, we'd now be publishing anyways-impact-toolbox-${{ steps.regex-match.outputs.group1 }}.zip && ls"
