name: staging
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Read metadata.txt
      id: metadata
      uses: juliangruber/read-file-action@v1
      with:
        path: ./metadata.txt
    - uses: actions-ecosystem/action-regex-match@v2
      id: regex-match
      with:
        text: ${{ steps.metadata.outputs.content }}
        regex: '^version=(.*)$'
    - name: Zip Folder
      run: zip -r impact-plugin-${{ steps.regex-match.outputs.group1 }}.zip . -x .git -x .github
    - name: Release to Github
      run: echo "Release"