name: staging
on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Build"
      uses: "./.github/actions/build-plugin"
    - name: "Detect correct zip file"
      run: |
        FILE=`ls anyways-impact-toolbox-[0-9.]*.zip`
        VERSION=`echo $FILE | sed "s/anyways-impact-toolbox-\([0-9.]*[0-9]\)-dev.zip/\1/"`
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "FILE=$FILE" >> $GITHUB_ENV
        
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "v${{ env.VERSION }}-dev"
        files: |
          LICENSE
          *.zip

    - name: Publish experimental version to QGIS repo.
      run: python ./deployment/plugin_upload.py -u xivk -w ${{ secrets.QGIS_REPO_SECRET }} ${{ env.FILE }}

