name: staging
on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Build"
      uses: "./.github/actions/build-plugin"
    - name: "Detect correct zip file"
      run |
        FILE=`ls anyways-impact-toolbox-[0-9.]*.zip`
        echo {FILE}={$FILE} >> $GITHUB_ENV
    - name: "print zipfile"
      run: "echo If this were a production build, we WOULD be pulishing $FILE"
